### ISSUE TITLE
pants fail to start when running using scie-pants on MacOS m1

### ISSUE THREAD

**Issue by asherf** [pantsbuild/scie-pants#76]
pants fail to start when running using scie-pants.

MacOS 13.1  on Apple m1.

```
❯ ./src/sh/pants/pantsup.sh
Downloading and installing the pants launcher ...
Installed the pants launcher from https://github.com/pantsbuild/scie-pants/releases/latest/download/scie-pants-macos-aarch64 to /Users/asher/bin/pants

Running `pants` in a Pants-enabled repo will use the version of Pants configured for that repo.
In a repo not yet Pants-enabled, it will prompt you to set up Pants for that repo.
❯ pants --version
12:06:48.92 [ERROR] 1 Exception encountered:

Engine traceback:
  in select
  in pants.init.plugin_resolver.resolve_plugins
  in construct_scope_
  in pants.engine.internals.options_parsing.scope_options
  in pants.engine.internals.options_parsing.parse_options
Traceback (most recent call last):
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/options_parsing.py", line 48, in parse_options
    return _Options(options_bootstrapper, build_config)
  File "<string>", line 5, in __init__
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/options_parsing.py", line 36, in __post_init__
    assert self.options is not None
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/util/memo.py", line 123, in memoize
    result = func(*args, **kwargs)
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/options_parsing.py", line 40, in options
    return self.options_bootstrapper.full_options(self.build_config)
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/option/options_bootstrapper.py", line 282, in full_options
    raise BuildConfigurationError(
pants.base.exceptions.BuildConfigurationError: Version mismatch: Requested version was 2.15.0rc2, our version is 2.14.0.dev3.
Traceback (most recent call last):
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/bin/daemon_pants_runner.py", line 130, in single_daemonized_run
    scheduler, options_initializer = self._core.prepare(options_bootstrapper, complete_env)
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/pantsd/pants_daemon_core.py", line 129, in prepare
    build_config, options = self._options_initializer.build_config_and_options(
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/init/options_initializer.py", line 107, in build_config_and_options
    build_config = _initialize_build_configuration(
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/init/options_initializer.py", line 47, in _initialize_build_configuration
    working_set = plugin_resolver.resolve(options_bootstrapper, env)
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/init/plugin_resolver.py", line 131, in resolve
    for resolved_plugin_location in self._resolve_plugins(
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/init/plugin_resolver.py", line 157, in _resolve_plugins
    session.product_request(ResolvedPluginDistributions, [request])[0],
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 577, in product_request
    return self.execute(request)
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 521, in execute
    self._raise_on_error([t for _, t in throws])
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/scheduler.py", line 498, in _raise_on_error
    raise ExecutionError(
pants.engine.internals.scheduler.ExecutionError: 1 Exception encountered:

Engine traceback:
  in select
  in pants.init.plugin_resolver.resolve_plugins
  in construct_scope_
  in pants.engine.internals.options_parsing.scope_options
  in pants.engine.internals.options_parsing.parse_options
Traceback (most recent call last):
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/options_parsing.py", line 48, in parse_options
    return _Options(options_bootstrapper, build_config)
  File "<string>", line 5, in __init__
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/options_parsing.py", line 36, in __post_init__
    assert self.options is not None
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/util/memo.py", line 123, in memoize
    result = func(*args, **kwargs)
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/engine/internals/options_parsing.py", line 40, in options
    return self.options_bootstrapper.full_options(self.build_config)
  File "/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants/option/options_bootstrapper.py", line 282, in full_options
    raise BuildConfigurationError(
pants.base.exceptions.BuildConfigurationError: Version mismatch: Requested version was 2.15.0rc2, our version is 2.14.0.dev3.


Use -ldebug for more logs.
See https://www.pantsbuild.org/v2.14/docs/troubleshooting for common issues.
Consider reaching out for help: https://www.pantsbuild.org/v2.14/docs/getting-help

 ~/projects/toolchain  costanza *2 
```

**Comment by asherf** [comment]
not sure where `2.14.0.dev3.` is coming from. we are using `2.15.0rc2` in the repo (this is the version in pants.toml):
![Screenshot 2023-01-26 at 12 09 58 PM](https://user-images.githubusercontent.com/1268088/214902262-6125a3e6-9071-458f-95d9-6a3a350a8249.png)

**Comment by jsirois** [comment]
@asherf if you can confirm that is true, I'll see if there is anything I can do, but there may not be. This is really all in Pants-land and not scie-pants if so.

**Comment by asherf** [comment]
> No such issue here:
> 
> ```
> jsirois@Gill-Windows:~/dev/toolchainlabs/toolchain (master) $ ./src/sh/pants/pantsup.sh
> Downloading and installing the pants launcher ...
> Installed the pants launcher from https://github.com/pantsbuild/scie-pants/releases/latest/download/scie-pants-linux-x86_64 to /home/jsirois/bin/pants
> 
> Running `pants` in a Pants-enabled repo will use the version of Pants configured for that repo.
> In a repo not yet Pants-enabled, it will prompt you to set up Pants for that repo.
> jsirois@Gill-Windows:~/dev/toolchainlabs/toolchain (master) $ pants --version
> 09:13:49.17 [INFO] Starting: Resolving plugins: chardet==5.0.0, requests>=2.28.1
> 09:13:50.97 [INFO] Completed: Resolving plugins: chardet==5.0.0, requests>=2.28.1
> 09:13:51.42 [INFO] Initializing scheduler...
> 09:13:52.01 [INFO] Scheduler initialized.
> 09:13:52.12 [WARN] Error loading access token: AuthError('[rule-construct-auth-store] Failed to load auth token (no default file or environment variable). Run `/home/jsirois/bin/pants auth-acquire` to set up authentication.')
> 09:13:52.12 [WARN] Auth failed - BuildSense plugin is disabled.
> 2.15.0rc2
> ```
> 
> So you must have `PANTS_VERSION` set somewhere in your environment?

nope... AFAICT
![Screenshot 2023-01-26 at 12 16 17 PM](https://user-images.githubusercontent.com/1268088/214904059-a19573f8-dd6a-43e4-b054-a62e1573439f.png)

**Comment by asherf** [comment]
if this is a pants issue, feel free to move the ticket.
we do still have the pants script (didn't touch it) but I don't think that is the issue (will check though)
I really have no idea where the 2.14.0 dev3 is coming from....

**Comment by asherf** [comment]
![Screenshot 2023-01-26 at 12 25 02 PM](https://user-images.githubusercontent.com/1268088/214905827-aa77a3a0-c329-4539-bd36-1b310b9ef408.png)

**Comment by asherf** [comment]
FWIW, this only happens on my mac, works just fine in CI and on a linux (ubuntu) machine.

**Comment by jsirois** [comment]
@asherf can you run this and report back?:
```
$ find ~/.cache/nce/*/locks -type f \! -name "*.lck" | while read f; do echo ">>> $f:" && cat $f && echo; done
>>> /home/jsirois/.cache/nce/99421dee8fedc336d5a6bb8322fbfa602bc68fe63303ae702ec7b9c5672cd086/locks/configure-9b2a25840f661b94baccd38fde68d58ffb4dce89265e003f1272352c0ad21452:
FIND_LINKS=file:///home/jsirois/.cache/nce/99421dee8fedc336d5a6bb8322fbfa602bc68fe63303ae702ec7b9c5672cd086/bindings/find_links/2.15.0rc2/4e0a3fd8/index.html
PANTS_BUILDROOT_OVERRIDE=/home/jsirois/dev/toolchainlabs/toolchain
PANTS_SHA_FIND_LINKS=--python-repos-find-links=-['file:///home/jsirois/.cache/nce/99421dee8fedc336d5a6bb8322fbfa602bc68fe63303ae702ec7b9c5672cd086/bindings/find_links/2.15.0rc2/4e0a3fd8/index.html']
PANTS_VERSION=2.15.0rc2
PYTHON=python3.9

>>> /home/jsirois/.cache/nce/99421dee8fedc336d5a6bb8322fbfa602bc68fe63303ae702ec7b9c5672cd086/locks/install-b385c33f90c9df3b8b70927af480371e86c3446190995ea2ad773bd2cf9573e3:
VIRTUAL_ENV=/home/jsirois/.cache/nce/99421dee8fedc336d5a6bb8322fbfa602bc68fe63303ae702ec7b9c5672cd086/bindings/venvs/2.15.0rc2

```

**Comment by jsirois** [comment]
The only relevant difference I can think of with scie-pants is it adds the feature of reading `.env` files when present in the build root or ancestor directories.

**Comment by jsirois** [comment]
The only other thing that strikes me is there are no pantsd startup log lines in your failure output. Can you do a `ps` and grab the lines with pantsd to save and then kill pantsd processes and try again?

**Comment by jsirois** [comment]
Aha. Oh Jesus:
```
/Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants
```

So that's a mouthful. I'm thinking about why that causes this, but its generally bad and there is your fix - don't install pants in a ~system interpreter manually.

**Comment by asherf** [comment]
> Aha. Oh Jesus:
> 
> ```
> /Users/asher/.pyenv/versions/3.9.12/lib/python3.9/site-packages/pants
> ```
> 
> So that's a mouthful. I'm thinking about why that causes this, but its generally bad and there is your fix - don't install pants in a ~system interpreter manually.

hmmmmm... not sure how pants got there.

I will wipe that python version from my machine and re-install it.

**Comment by asherf** [comment]
![Screenshot 2023-01-26 at 12 51 37 PM](https://user-images.githubusercontent.com/1268088/214911346-af4fb70f-69c4-429f-8029-d557322dee4a.png)
that fixed it.
closing ticket.
